### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by max-logvyniuk** [iKala/gorm-cli#1]
This feature looks promising) Whether it is possible to add any documentation on use?

**Comment by salemzii** [comment]
Great idea @max-logvyniuk, it'd be great to have a little "how it works" documentation for newbies

**Comment by g4ru04** [comment]
Thanks for raise that !
Hope that this PR can help you about this

[https://github.com/iKala/gorm-cli/pull/7](https://github.com/iKala/gorm-cli/pull/7)
